# Generated by Django 3.2.18 on 2023-03-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aproved',
            new_name='approved',
        ),
    ]
